/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./componant/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      backgroundImage: {},
      colors: {
        NavbarBackground: "#0E1C50",
        bgButtonNavbar: "#D3B472",
        bgButtonHeader: "#BDA97F",
        bgHeader: "#E1E6F880",
        oneTextHeader: "#2E344A",
        twoTextHeader: "#656262",
        bgKnowUs: "#F6F0E3",
        bgOfferWork: "#CFD2DC",
        bgContactUs: "#EDEDED",
        bgPop: "#E1E6F8",
        textInput: "#656262",
        forgetPasswordText: "#BDA97F",
        bgIconQuestion: "#ED5A46",
        bgIconSuccess: "#61CE70",
        textFilter: "#706E6E",
        insideTextFilter: "#4A4848",
        bgwhite: "#0000004D",
        bgButtonPagination: "#EDC165EB",
        bgButtonPaginationActive: "#BDA97F",
        textHeadOfferWork: "#0E1C50",
        green: "#61CE70",
        red: "#ED5A46",
        oddTable: "#F8F3F3",
        evenTable: "#EEEEEE",
        bgTable: "#F7F7F7",
        bgHover: "#192C72",
        bgTableDashboard: "#F6F2F2",
        textLabelSelect: "#4A4848",
      },
      screens: {
        smm: { min: "100px", max: "600px" },
        smml: { min: "10px", max: "1024px" },
      },
    },
  },
  plugins: [],
};
